### ISSUE TITLE
Definição do Modelo que será utilizado

### ISSUE THREAD

**Issue by MarcielTorres** [MarcielTorres/serverless-crud-app#1]
A ideia aqui é discutir eventuais modelos e estrutura de dados que poderão ser utilizados para demonstração. Minha sugestão é utilizar um tipo de estrutura complexa com diversos modelos de dados, seguem algumas ideias:

- Cadastro de Produtos
- Cadastro de Veículos
- Cadastro de Pessoa Física e Jurídica

**Comment by cantoniazzi** [comment]
@MarcielTorres eu acho que estes são cadastros interessantes para um primeiro momento, em especial ao modelo de cadastro de Pessoa especializando com o tipo Física/Jurídica.

Acho que podemos generalizar e deixar apenas um cadastro de Produtos com a possibilidade cadastrar categorias, fabricantes, etc. Já fica padronizado e não precisaríamos cadastrar outras coisas, pois tudo poderia ser abstraído para um cadastro de produto.

**Comment by MarcielTorres** [comment]
Modelo de dados e mais informações disponíveis em:
https://github.com/MarcielTorres/serverless-crud-app/wiki/Modelagem-de-Dados
